CU-8678g1zd5 - neo3-signer / neon-signer: encrypt, decrypt and decryp…
CityOfZion/neo3-signer pull request #3
Opened 2023-08-04 21:34 UTC by luc10921

…tFromArray methods

2023-08-04 21:34 UTC, melanke commented
Task linked: [CU-8678g1zd5 neo3-signer / neon-signer: encrypt, decrypt and decryptFromArray methods](https://app.clickup.com/t/8678g1zd5)

2023-08-07 13:32 UTC, melanke requested changes
This is great! Thank you so much, very good job :)
I am asking Rick to take a quick look at it as well, but there is a few tests that can be slightly improved

2023-08-07 13:32 UTC, melanke commented on packages/neon-signer/src/index.spec.ts
> +    assert(messageDecrypted === messageOriginal)
put another test here to ensure the messageOriginal is different from messageEncrypted[0] pls

2023-08-07 13:32 UTC, melanke commented on packages/neon-signer/src/index.spec.ts
> +    const messageDecrypted = signer.decryptFromArray(messageEncrypted)
create another test where the encrypt is not using the same account to decrypt but it works anyway.

2023-08-07 13:39 UTC, lock9 requested changes

2023-08-07 13:39 UTC, lock9 commented on packages/neo3-signer/dist/index.d.ts
> +    ephemPublicKey: string;
O que é ephemPublicKey? Esse nome ta meio estranho, nao?

2023-08-07 13:39 UTC, lock9 commented on packages/neo3-signer/dist/index.d.ts
> +    encrypt(message: string, publicKeys: string[]): EncryptedPayload[];
Onde estao as configuracoes usadas no encrypto e decrypt? Geralmente os parametros sao descritos em algum lugar. Tipo, a curva que é usada e outros parametros poderiam ficar mais evidentes. Nao tem nenhuma garantia que quem implementar o encrypt vai conseguir usar o decrypt de outra implementacao

2023-08-07 13:39 UTC, lock9 commented on packages/neon-signer/dist/index.js
> +        const curve = new elliptic.ec('p256');
Justamente aqui que mora o problema.  Se usar outra curva vai dar problema. Precisa ficar explicito qual é a curva que usa (ou permitir parametros, nao sei)

2023-08-07 13:39 UTC, lock9 commented on packages/neon-signer/dist/index.js
> +            const cipher = crypto.createCipheriv('aes-256-cbc', encryptionKey, iv);
Mesma coisa aqui. Esses parametros vao funcionar com Ethereum e nao com Neo. Na pratica, esse codigo nao ta integrado com a blockchain, entao nao faria muita diferença. A questao é que em geral, a Neo usa outra curva. Ou seja: essas assinaturas produzidas usando essas curvas não passariam no "verify' da Neo. Eu nao sei se a Neo suporta outra curva alem da secp256r1.

2023-08-07 13:39 UTC, lock9 commented on packages/neon-signer/dist/index.js
> +        const cipher = crypto.createDecipheriv('aes-256-cbc', encryptionKey, Buffer.from(payload.randomVector, 'hex'));
Mesma coisa aqui. iNclusive, melhor tirar esses nomes dos algoritimos daqui e por em uma variavel. Se forem diferentes, nao vai funcionar.

2023-08-07 13:39 UTC, lock9 commented on packages/neon-signer/src/index.ts
> +    throw new Error('Could not decrypt message from array')
Esse código ta meio esquisito, nao?  É um for, que retorna no meio do loop. Tem um try catch tb. No minimo falta documentacao, olhando assim ta esquisitinho

2023-08-07 13:41 UTC, melanke commented on packages/neon-signer/dist/index.js
> +        const curve = new elliptic.ec('p256');
talvez a gente possa alterar o nome do método para `encryptP256`

2023-08-07 13:43 UTC, melanke commented on packages/neon-signer/dist/index.js
> +            const cipher = crypto.createCipheriv('aes-256-cbc', encryptionKey, iv);
Obrigado por pegar isso

2023-08-07 13:46 UTC, melanke commented on packages/neon-signer/src/index.ts
> +    throw new Error('Could not decrypt message from array')
A documentação está aqui: https://github.com/CityOfZion/neo3-signer/pull/3/files/c1995d054595db8de4de714e8469e7be6df609b2#diff-feeb5a0473167798d8c1f79943ec5cc0f53953da5205a9a3c7ee54ff7472290cR89

2023-08-07 13:48 UTC, melanke commented on packages/neo3-signer/dist/index.d.ts
> +    encrypt(message: string, publicKeys: string[]): EncryptedPayload[];
Eu que sugeri uma assinatura pro método, mas vc está certo, talvez precise de parâmetros, ou a gente "force" ter uma implementação só deixando mais claro no nome do método, vamos discutir isso nas outras threads.

2023-08-07 13:51 UTC, lock9 commented on packages/neon-signer/dist/index.js
> +        const curve = new elliptic.ec('p256');
Entao, depende mais se vc tem a curva implementada na camada de criptografia. Se a lib que usamos tem suporte, entao é só trocar a string mesmo. Senao, ai fudeu. Pode ser que precise de grandes ajustes, até usar outra lib de cryptografia. Acho que o ideal é ter algum tipo de enum, nao sei. Acho que string solta é ruim para usar (nao fica tipado)

2023-08-07 13:52 UTC, lock9 commented on packages/neon-signer/src/index.ts
> +    throw new Error('Could not decrypt message from array')
Entao, mas ta meio esquisito, nao? Tipo, ele tenta descriptografar todas as mensagens, mas assim que encontrar a primeira ele ja retorna? E se tiver mais de uma mensagem com a mesma public key?

2023-08-07 13:52 UTC, luc10921 commented on packages/neon-signer/dist/index.js
> +            const cipher = crypto.createCipheriv('aes-256-cbc', encryptionKey, iv);
Na documentação deles eles falam que aceitam por causa do cross-chain, eu achei que significava que eles aceitavam em qualquer momento, mas agora fiquei em duvida.
> In addition, to support the cross-chain transaction verification, Neo introduces the SECP256K1 curve with parameters
https://developers.neo.org/docs/n3/foundation/Cryptography/encryption_algorithm#ecc-algorithm

2023-08-07 14:01 UTC, luc10921 commented on packages/neo3-signer/dist/index.d.ts
> +    ephemPublicKey: string;
é a public key efêmera, que foi criada aleatoriamente pra ser utilizada no algoritmo de encriptação

2023-08-07 14:05 UTC, melanke commented on packages/neon-signer/dist/index.js
> +        const curve = new elliptic.ec('p256');
Sim, podemos resolver isso com typescript, passa um valor q precisa estar dentre um conjunto de valores

2023-08-07 14:15 UTC, lock9 commented on packages/neo3-signer/dist/index.d.ts
> +    ephemPublicKey: string;
Mas pq vc criaria uma public key efemera? se vc criptografar algo com ela sem ter a private key, vc vai perder os dados, nao?

2023-08-07 14:16 UTC, lock9 commented on packages/neon-signer/dist/index.js
> +            const cipher = crypto.createCipheriv('aes-256-cbc', encryptionKey, iv);
Provavelmente tem parametro pra falar a curva que vc quer usar. Inclusive tem que ver se o Neo Boa suporta

2023-08-07 14:17 UTC, lock9 commented on packages/neon-signer/src/index.ts
> +    throw new Error('Could not decrypt message from array')
É que parece que esse metodo descriptografa várias mensagens (lendo a assinatura). Na pratica, ele acha uma mensagem la no meio e traz só ela

2023-08-16 17:45 UTC, melanke approved these changes
Dos pontos que eu trouxe foram todos corrigidos. Aquela parada de ter multiplas implementações de criptografia a gente vai deixar qto e só especificar na documentação né?

2023-08-16 17:51 UTC, merged